# Use postgres/example user/password credentials
version: '3.18'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=somebody
      - POSTGRES_PASSWORD=012345
    volumes:
      - ./data:/var/lib/postgresql/
    ports:
      - '5432:5432'